- name: Project
  description: 'This is a project'
  light_ico: '../../media/project_explorer/light/project.svg'
  dark_ico: '../../media/project_explorer/dark/project.svg'
  children: ['UMLPackage']
  properties:
    version:
      type: 'input'
      value: ''

- name: UMLPackage
  description: 'This is a package'
  light_ico: '../../media/project_explorer/light/package.svg'
  dark_ico: '../../media/project_explorer/dark/package.svg'
  children: ['UMLClass']
  properties:
    version:
      type: 'input'
      value: ''
      
- name: UMLClass
  description: 'This is a class'
  light_ico: '../../media/project_explorer/light/class.svg'
  dark_ico: '../../media/project_explorer/dark/class.svg'
  children: ['UMLOperation']
  properties:
    version:
      type: 'input'
      value: ''
    primaryColor:
      type: 'input'
      value: ''
    secondaryColor:
      type: 'input'
      value: ''
    users:
      type: 'dropdown'
      value: []
    isActive:
      type: 'checkbox'
      value: false
    searchUsers: 
      type: 'nav'
      value: ''
      
- name: UMLOperation
  description: 'This is an operation'
  light_ico: '../../media/project_explorer/light/operation.svg'
  dark_ico: '../../media/project_explorer/dark/operation.svg'
  properties:
    version:
      type: 'input'
      value: ''
    primaryColor:
      type: 'input'
      value: ''
    secondaryColor:
      type: 'input'
      value: ''
    users:
      type: 'dropdown'
      value: []
    isActive:
      type: 'checkbox'
      value: false
    searchUsers: 
      type: 'nav'
      value: ''